name: 'Create release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: './.github/actions/prepare-build-env'
      - name: create release ${{ inputs.version }}
        id: release
        env:
          NEW_VER: ${{ inputs.version }}
        run: |
          NEW_TAG="v$NEW_VER"
          pnpm bump-version $NEW_VER
          pnpm install
          cd src-tauri && cargo generate-lockfile && cd ..
          pnpm format
          pnpm lint
          pnpm check
          git checkout -b release/$NEW_TAG
          git commit -a -m"Release v$NEW_VER"
          git push -u origin release/$NEW_TAG
      - name: Create Draft Release
        run: |
          gh release create $NEW_TAG \
            --draft \
            --title "Release $NEW_TAG" \
            --notes "See the assets to download this version and install."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
