name: Publish release artifacts

on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #   args: '--verbose --target aarch64-apple-darwin'
          #   platform-name: 'Macos-M1'
          # - platform: 'macos-latest' # for Intel based macs.
          #   args: '--verbose --target x86_64-apple-darwin'
          #   platform-name: 'Macos-Intel'
          - platform: 'macos-latest' # for Univrsal based macs.
            args: '--verbose --target universal-apple-darwin'
            platform-name: 'Macos-Universal'
          - platform: 'ubuntu-latest' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: '--verbose'
            platform-name: 'Linux'
          - platform: 'windows-latest'
            args: '--verbose'
            platform-name: 'Windows'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: './.github/actions/prepare-build-env'
      - uses: bluwy/substitute-string-action@v3
        with:
          _input-file: 'src-tauri/src/main.rs'
          _output-file: 'src-tauri/src/main.rs'
          _format-key: '%%key%%'
          PROFILE: 'release'
          WOMBAT_API_URL: ${{ secrets.WOMBAT_API_URL }}
          WOMBAT_API_USER: ${{ secrets.WOMBAT_API_USER }}
          WOMBAT_API_PASSWORD: ${{ secrets.WOMBAT_API_PASSWORD }}
      - name: Get version
        id: version
        shell: bash
        run: |
          NEW_VERSION="$(node read-version.js)"
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: '${{steps.vars.outputs.NEW_VERSION}}' # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: '${{steps.vars.outputs.NEW_VERSION}}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
