name: Publish release artifacts

on:
  push:
    branches:
      - release/**

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Univrsal based macs.
          #   args: '--verbose --target universal-apple-darwin'
          #   platform-name: 'Macos-Universal'
          - platform: 'macos-latest'
            args: '--debug --target aarch64-apple-darwin'
            platform-name: 'Macos-latest'
          - platform: 'ubuntu-latest'
            args: '--debug'
            platform-name: 'Linux'
          - platform: 'windows-latest'
            args: '--debug'
            platform-name: 'Windows'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: './.github/actions/prepare-build-env'
      - name: Extract version tag from branch name
        id: get_version_tag
        run: |
          TAG_NAME=$(echo "${{ github.ref_name }}" | sed 's|release/||')
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
        shell: bash
      - uses: bluwy/substitute-string-action@v3
        with:
          _input-file: 'src-tauri/src/main.rs'
          _output-file: 'src-tauri/src/main.rs'
          _format-key: '%%key%%'
          PROFILE: 'release'
          WOMBAT_API_URL: ${{ secrets.WOMBAT_API_URL }}
          WOMBAT_API_USER: ${{ secrets.WOMBAT_API_USER }}
          WOMBAT_API_PASSWORD: ${{ secrets.WOMBAT_API_PASSWORD }}
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          WOMBAT_API_URL: ${{ secrets.WOMBAT_API_URL }}
          WOMBAT_API_USER: ${{ secrets.WOMBAT_API_USER }}
          WOMBAT_API_PASSWORD: ${{ secrets.WOMBAT_API_PASSWORD }}
        with:
          tagName: '${{ steps.get_version_tag.outputs.tag }}' # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: '${{ steps.get_version_tag.outputs.tag }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
